[package]
name = "iqfit"
version = "0.1.0"
authors = ["Valentin Tolmer <valentin.tolmer@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
modular-bitfield = "~0.11"
colored = "2"
